criterion: 
  - L1Loss
  - MSELoss
epochs: 
  - 20
learning_rate: 
  - 0.001
  - 0.1
#  - 10.0
optimizer:
  - Adam
  - SGD
#  - Adagrad
reduction:
  - mean
#  - sum
weight_decay:
# Hint from Stanford: 0.0001 is too low; scales linearly with batch size
  - 0.01
  - 0.1
clip_value:
  - 0.2
  - 0.5
batch_size:
  - 32
  - 64
test_threshold: 1.0
shuffle: true
device: cuda
cudnn_enabled: true
training_steps:
  - train
  - valid
  - test
conv_config: config\conv_config.yaml
dl_config: config\dl_config_win.yaml
net_config: config\net_config_win.yaml
score_data: ./config/score.yaml