criterion: L1Loss
cudnn_enabled: false
device: cpu
epochs: 10
learning_rate: 1.0
optimizer: Adam
reduction: mean
test_threshold: 1.0
weight_decay: 1.0e-05
shuffle: false
training_steps:
  - train
  - valid
  - test
conv_config: config/conv_config.yaml
dl_config: config/dl_config.yaml
net_config: config/net_config.yaml
