criterion: 
  - L1Loss
  - MSELoss
epochs: 
  - 20
learning_rate: 
  - 10.0
  - 0.1
  - 0.001
optimizer:
  - Adam
#  - SGD
#  - Adagrad
reduction:
  - mean
  - sum
weight_decay:
  - 0.0
  - 0.001
batch_size:
  - 32
clip_value:
  - 0
  - 1.0
test_threshold: 1.0
shuffle: false
device: cuda
cudnn_enabled: false
training_steps:
  - train
  - valid
  - test
conv_config: config/conv_config.yaml
dl_config: config/dl_config_win.yaml
net_config: config/net_config.yaml
score_data: config/score.yaml