criterion: 
  - L1Loss
#  - MSELoss
epochs: 
  - 10
  - 100
learning_rate: 
  - 0.01
  - 0.001
optimizer:
  - Adam
  - SGD
  - Adagrad
reduction:
#  - mean
  - sum
weight_decay:
  - 0.01
  - 0.001
batch_size:
  - 32
test_threshold: 1.0
shuffle: false
device: cpu
cudnn_enabled: false
training_steps:
  - train
  - valid
  - test
conv_config: config/conv_config.yaml
dl_config: config/dl_config_hw.yaml
net_config: config/net_config_hw.yaml
score_data: config/score_hw.yaml